[package]
name = "entity"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "entity"
path = "src/mod.rs"

[dependencies]
serde = { version = "1.0.204", features = ["derive"] }

[dependencies.sea-orm]
version = "1.0.0"