//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "role")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub deleted: bool,
    pub name: String,
    pub administrator: bool,
    pub manage_users: bool,
    pub manage_channels: bool,
    pub manage_roles: bool,
    pub organization_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::channel_role_access::Entity")]
    ChannelRoleAccess,
    #[sea_orm(
        belongs_to = "super::organization::Entity",
        from = "Column::OrganizationId",
        to = "super::organization::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Organization,
    #[sea_orm(has_many = "super::user_role_access::Entity")]
    UserRoleAccess,
}

impl Related<super::channel_role_access::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChannelRoleAccess.def()
    }
}

impl Related<super::organization::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organization.def()
    }
}

impl Related<super::user_role_access::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserRoleAccess.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
